/**
 * Renders both reports from fixture data straight to a file, with no Worker
 * and no database.
 *
 * The layout is the half of this feature that no assertion can really check:
 * a test can prove the bytes begin `%PDF-` and that the totals are right, and
 * still be describing a document whose columns overlap. This produces real
 * files to look at.
 *
 * Run: npx esbuild scripts/preview-report.ts --bundle --platform=node \
 *        --format=esm --outfile=<tmp>/preview.mjs && node <tmp>/preview.mjs <outdir>
 */
import { writeFileSync } from 'node:fs';
import { StatementDoc } from '../src/statements/layout';
import { renderJournal, renderLedger } from '../src/statements/reports-render';
import type { JournalReport, LedgerReport } from '../src/statements/reports';

const outDir = process.argv[2] || '.';

const meta = (title: string, subtitle: string) => ({
  title,
  subtitle,
  organisation: 'Godwin Austen Labs (Private) Limited  ·  NTN 1234567-8',
  currency: 'PKR',
  provenance:
    'Generated by Pleiades from general_journals on 2026-09-15 10:00 UTC · ' +
    'requested by Saad Naik · amounts in PKR',
  draft: true,
});

const entry = (
  id: string, date: string | null, description: string,
  lines: { accountName: string; type: 'debit' | 'credit'; amount: number }[],
  extra: Partial<{ ledgerName: string | null; invoiceId: string | null }> = {},
) => {
  const debit = lines.filter((l) => l.type === 'debit').reduce((s, l) => s + l.amount, 0);
  const credit = lines.filter((l) => l.type === 'credit').reduce((s, l) => s + l.amount, 0);
  return {
    id, entryDate: date, description,
    ledgerName: extra.ledgerName ?? 'Main Ledger',
    invoiceId: extra.invoiceId ?? null,
    lines: lines.map((l) => ({ ...l, accountId: l.accountName })),
    debit, credit, balanced: Math.abs(debit - credit) < 0.01,
  };
};

const entries = [
  entry('jrn_0a1b2c3d4e5f60718293a4b5c6d7e8f9', '2026-01-10',
    'Retainer invoiced to Acme Holdings for Q1 advisory work, settled by bank transfer the same day under agreement AH-2026-004',
    [{ accountName: 'Cash at bank', type: 'debit', amount: 1250000 },
     { accountName: 'Consulting fee income', type: 'credit', amount: 1250000 }],
    { invoiceId: 'inv_77a2b1' }),
  entry('jrn_1a1b2c3d4e5f60718293a4b5c6d7e8f9', '2026-01-31', 'Office rent and utilities, January',
    [{ accountName: 'Office rent and utilities', type: 'debit', amount: 185000 },
     { accountName: 'Cash at bank', type: 'credit', amount: 185000 }]),
  // Compound, and with text the standard fonts cannot encode.
  entry('jrn_2a1b2c3d4e5f60718293a4b5c6d7e8f9', '2026-02-05',
    'Café — “quarterly” settlement ₨ 🎉 split three ways between rent, fees and the director loan',
    [{ accountName: 'Office rent and utilities', type: 'debit', amount: 40000 },
     { accountName: 'Consulting fee income', type: 'debit', amount: 10000 },
     { accountName: 'Cash at bank', type: 'credit', amount: 35000 },
     { accountName: 'Director loan account', type: 'credit', amount: 15000 }]),
  entry('jrn_3a1b2c3d4e5f60718293a4b5c6d7e8f9', '2026-02-20', 'Short posting',
    [{ accountName: 'Office rent and utilities', type: 'debit', amount: 5000 },
     { accountName: 'Cash at bank', type: 'credit', amount: 4000 }]),
  entry('jrn_4a1b2c3d4e5f60718293a4b5c6d7e8f9', null, 'Undated adjustment carried over from the old system',
    [{ accountName: 'Office rent and utilities', type: 'debit', amount: 1000 },
     { accountName: 'Cash at bank', type: 'credit', amount: 1000 }]),
  ...Array.from({ length: 45 }, (_, i) =>
    entry(`jrn_b${String(i).padStart(31, '0')}`, `2026-03-${String((i % 28) + 1).padStart(2, '0')}`,
      `Sundry expense ${i} paid from the current account`,
      [{ accountName: 'Office rent and utilities', type: 'debit', amount: 1000 + i },
       { accountName: 'Cash at bank', type: 'credit', amount: 1000 + i }])),
];

// Sorted as `journalReport` sorts: by date, undated last. The renderer is
// handed an ordered list and does not sort, so a preview that fed it fixture
// order would be showing a layout the real report never produces.
entries.sort((a, b) => {
  const ad = a.entryDate || '\uffff';
  const bd = b.entryDate || '\uffff';
  return ad === bd ? (a.id < b.id ? -1 : 1) : ad < bd ? -1 : 1;
});

const totalDebit = entries.reduce((s, e) => s + e.debit, 0);
const totalCredit = entries.reduce((s, e) => s + e.credit, 0);

const journal: JournalReport = {
  range: { startDate: null, endDate: null },
  ledgerId: null, ledgerName: null,
  entries: entries as any,
  entryCount: entries.length + 12,
  omitted: 12,
  truncated: true,
  totalDebit, totalCredit,
  unbalanced: 1, undated: 1, empty: false,
};

const ledgerEntries = (n: number, from: number) => {
  let balance = from;
  return Array.from({ length: n }, (_, i) => {
    const debit = i % 3 === 0 ? 125000 + i * 37 : 0;
    const credit = i % 3 === 0 ? 0 : 18500 + i * 11;
    balance = Math.round((balance + debit - credit) * 100) / 100;
    return {
      id: `jrn_c${String(i).padStart(31, '0')}`,
      entryDate: `2026-0${(i % 6) + 1}-${String((i % 28) + 1).padStart(2, '0')}`,
      description: i % 4 === 0
        ? 'Quarterly settlement against the advisory retainer, net of withholding'
        : 'Routine payment',
      contra: i % 5 === 0
        ? 'Consulting fee income, Director loan account'
        : 'Office rent and utilities',
      debit, credit, balance,
    };
  });
};

const account = (name: string, type: string, n: number, opening: number) => {
  const es = ledgerEntries(n, opening);
  const td = es.reduce((s, e) => s + e.debit, 0);
  const tc = es.reduce((s, e) => s + e.credit, 0);
  return {
    accountId: name, accountName: name, accountType: type, ledgerName: 'Main Ledger',
    openingBalance: opening, entries: es, entryCount: n, omitted: 0, truncated: false,
    totalDebit: td, totalCredit: tc,
    closingBalance: Math.round((opening + td - tc) * 100) / 100,
  };
};

const accounts = [
  account('Cash at bank', 'asset', 34, 1250000),
  account('Consulting fee income', 'revenue', 18, -4400000),
  account('Office rent and utilities', 'expense', 9, 0),
  account('Director loan account', 'liability', 4, -15000),
];

const ledger: LedgerReport = {
  scope: 'all', scopeLabel: 'All ledger accounts',
  range: { startDate: '2026-01-01', endDate: '2026-06-30' },
  accounts,
  skippedEmpty: 2,
  totalDebit: accounts.reduce((s, a) => s + a.totalDebit, 0),
  totalCredit: accounts.reduce((s, a) => s + a.totalCredit, 0),
  net: accounts.reduce((s, a) => s + a.totalDebit - a.totalCredit, 0),
  truncated: false, empty: false,
};

const jDoc = await StatementDoc.create(meta('General Journal', 'Complete history — every entry on record'));
renderJournal(jDoc, journal);
writeFileSync(`${outDir}/journal.pdf`, await jDoc.save());

const lDoc = await StatementDoc.create(
  meta('Ledger — All Accounts', 'For the period 1 January 2026 to 30 June 2026'));
renderLedger(lDoc, ledger);
writeFileSync(`${outDir}/ledger.pdf`, await lDoc.save());

console.log('wrote journal.pdf and ledger.pdf');
