PRAGMA foreign_keys = OFF;
-- ============================================================
-- office RBAC Seed — auto-generated by scratch/seed_rbac.ts
-- ============================================================

-- 1. Roles
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-ceo', 'CEO', 1779861526);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-director', 'Director', 1779861526);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-legal', 'Legal_Officer', 1779861526);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-emp', 'Employee', 1779861526);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-agent', 'Agent', 1779861526);

-- 2. Role Hierarchy (Skipped)

-- 3. Permissions
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-employee', 'view_employee', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-employee', 'edit_employee', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-delete-employee', 'delete_employee', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-payroll', 'view_payroll', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-payroll', 'edit_payroll', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-appointments', 'view_appointments', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-appointments', 'edit_appointments', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-legal-tracker', 'view_legal_tracker', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-legal-tracker', 'edit_legal_tracker', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-sectors', 'view_sectors', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-sectors', 'edit_sectors', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-transactions', 'view_transactions', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-create-transaction', 'create_transaction', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-approve-transaction', 'approve_transaction', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-invoices', 'view_invoices', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-create-invoice', 'create_invoice', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-fund-requests', 'view_fund_requests', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-approve-fund-request', 'approve_fund_request', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-accounts', 'view_accounts', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-accounts', 'edit_accounts', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-pl-reports', 'view_pl_reports', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-agreements', 'view_agreements', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-create-agreement', 'create_agreement', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-sign-agreement', 'sign_agreement', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-compliance', 'view_compliance', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-compliance', 'edit_compliance', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-ip', 'view_ip', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-ip', 'edit_ip', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-projects', 'view_projects', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-projects', 'edit_projects', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-tasks', 'view_tasks', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-create-task', 'create_task', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-task', 'edit_task', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-deployments', 'view_deployments', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-trigger-deployment', 'trigger_deployment', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-campaigns', 'view_campaigns', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-campaigns', 'edit_campaigns', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-leads', 'view_leads', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-leads', 'edit_leads', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-provision-user', 'provision_user', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-deactivate-user', 'deactivate_user', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-approve-reset', 'approve_reset', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-reassign-ownership', 'reassign_ownership', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-audit-logs', 'view_audit_logs', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-manage-roles', 'manage_roles', 1779861526);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-manage-api-keys', 'manage_api_keys', 1779861526);

-- 4. Role ↔ Permission grants (Skipped)

-- 5. CEO user account
INSERT OR IGNORE INTO users_logins (id, email, username, name, password_hash, role_id, is_active, created_at, failed_attempts) VALUES ('user-ceo-001', 'ceo@godwinausten.org', 'ceo', 'Saad Naik', 'c2d5d46c76a18cd23a4a1d0c27ae02335b0a992561c5dd084db14f6441e3a3ec', 'role-ceo', 1, 1779861526, 0);
UPDATE users_logins SET username = 'ceo', name = 'Saad Naik' WHERE id = 'user-ceo-001';

-- 6. HR Manager user account
INSERT OR IGNORE INTO users_logins (id, email, username, name, password_hash, role_id, is_active, created_at, created_by_user_id, failed_attempts) VALUES ('user-hr-001', 'hr@godwinausten.org', 'hrmanager', 'HR Manager', 'e0fb69c10d32ede2acf1e081c2d7ac65c006e4e69680e077d0baf180d7d3b9d3', 'role-hr', 1, 1779861526, 'user-ceo-001', 0);
UPDATE users_logins SET username = 'hrmanager', name = 'HR Manager' WHERE id = 'user-hr-001';

-- 7. CEO owns HR Manager (CEO owns themselves too, for symmetry)
INSERT OR IGNORE INTO user_ownership (user_id, owner_user_id, assigned_at, assigned_by_user_id) VALUES ('user-ceo-001', 'user-ceo-001', 1779861526, 'user-ceo-001');
INSERT OR IGNORE INTO user_ownership (user_id, owner_user_id, assigned_at, assigned_by_user_id) VALUES ('user-hr-001', 'user-ceo-001', 1779861526, 'user-ceo-001');

-- 8. App Access
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_hr', 'user-ceo-001', 'hr', 'admin', 1779861526);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_finance', 'user-ceo-001', 'finance', 'admin', 1779861526);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_legal', 'user-ceo-001', 'legal', 'admin', 1779861526);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_ops', 'user-ceo-001', 'ops', 'admin', 1779861526);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_acquisition', 'user-ceo-001', 'acquisition', 'admin', 1779861526);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_tech', 'user-ceo-001', 'tech', 'admin', 1779861526);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_hr_hr', 'user-hr-001', 'hr', 'admin', 1779861526);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_hr_ops', 'user-hr-001', 'ops', 'admin', 1779861526);

-- 9. CEO Granular Permissions (Full Access)
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_hr_employees', 'user-ceo-001', 'hr', 'employees', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_hr_appointments', 'user-ceo-001', 'hr', 'appointments', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_hr_payroll', 'user-ceo-001', 'hr', 'payroll', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_hr_resets', 'user-ceo-001', 'hr', 'resets', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_hr_tasks', 'user-ceo-001', 'hr', 'tasks', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_finance_transactions', 'user-ceo-001', 'finance', 'transactions', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_finance_invoices', 'user-ceo-001', 'finance', 'invoices', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_finance_fund_requests', 'user-ceo-001', 'finance', 'fund_requests', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_finance_accounts', 'user-ceo-001', 'finance', 'accounts', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_finance_pl_reports', 'user-ceo-001', 'finance', 'pl_reports', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_legal_agreements', 'user-ceo-001', 'legal', 'agreements', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_legal_compliance', 'user-ceo-001', 'legal', 'compliance', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_legal_ip', 'user-ceo-001', 'legal', 'ip', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_legal_requests', 'user-ceo-001', 'legal', 'requests', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_legal_sops', 'user-ceo-001', 'legal', 'sops', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_legal_templates', 'user-ceo-001', 'legal', 'templates', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_tech_projects', 'user-ceo-001', 'tech', 'projects', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_tech_tasks', 'user-ceo-001', 'tech', 'tasks', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_tech_deployments', 'user-ceo-001', 'tech', 'deployments', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_tech_issues', 'user-ceo-001', 'tech', 'issues', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_tech_releases', 'user-ceo-001', 'tech', 'releases', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_tech_environments', 'user-ceo-001', 'tech', 'environments', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_acquisition_campaigns', 'user-ceo-001', 'acquisition', 'campaigns', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_acquisition_leads', 'user-ceo-001', 'acquisition', 'leads', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_acquisition_content', 'user-ceo-001', 'acquisition', 'content', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_acquisition_funnels', 'user-ceo-001', 'acquisition', 'funnels', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_ops_core', 'user-ceo-001', 'ops', 'core', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_ops_admin', 'user-ceo-001', 'ops', 'admin', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_ops_audit', 'user-ceo-001', 'ops', 'audit', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_crm_tickets', 'user-ceo-001', 'crm', 'tickets', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_crm_planner', 'user-ceo-001', 'crm', 'planner', 1, 1, 1, 1779861526, 1779861526);
INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) VALUES ('perm_ceo_crm_docs', 'user-ceo-001', 'crm', 'docs', 1, 1, 1, 1779861526, 1779861526);

PRAGMA foreign_keys = ON;

-- ✅ Seed complete.
-- CEO:        ceo@godwinausten.org / ChangeMe_CEO_2026!
-- HR Manager: hr@godwinausten.org / ChangeMe_HR_2026!
-- IMPORTANT: Change passwords immediately after first login!
