PRAGMA foreign_keys = OFF;
-- ============================================================
-- GAnovaOS RBAC Seed — auto-generated by scratch/seed_rbac.ts
-- ============================================================

-- 1. Roles
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-ceo', 'CEO', 1778431328);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-hr', 'HR_Manager', 1778431328);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-finance', 'Finance_Manager', 1778431328);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-legal', 'Legal_Officer', 1778431328);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-tech', 'Tech_Lead', 1778431328);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-acq', 'Marketing_Lead', 1778431328);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-emp', 'Employee', 1778431328);
INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('role-agent', 'Agent', 1778431328);

-- 2. Role Hierarchy
INSERT OR IGNORE INTO role_hierarchy (role_id, level, can_provision_role_ids, allowed_modules, created_at) VALUES ('role-ceo', 1, '["role-ceo","role-hr","role-finance","role-legal","role-tech","role-acq","role-emp","role-agent"]', '["hr","finance","legal","ops","acquisition","tech","mcp_server"]', 1778431328);
UPDATE role_hierarchy SET level = 1, can_provision_role_ids = '["role-ceo","role-hr","role-finance","role-legal","role-tech","role-acq","role-emp","role-agent"]', allowed_modules = '["hr","finance","legal","ops","acquisition","tech","mcp_server"]' WHERE role_id = 'role-ceo';
INSERT OR IGNORE INTO role_hierarchy (role_id, level, can_provision_role_ids, allowed_modules, created_at) VALUES ('role-hr', 2, '["role-finance","role-legal","role-tech","role-acq","role-emp"]', '["hr","ops","mcp_server"]', 1778431328);
UPDATE role_hierarchy SET level = 2, can_provision_role_ids = '["role-finance","role-legal","role-tech","role-acq","role-emp"]', allowed_modules = '["hr","ops","mcp_server"]' WHERE role_id = 'role-hr';
INSERT OR IGNORE INTO role_hierarchy (role_id, level, can_provision_role_ids, allowed_modules, created_at) VALUES ('role-finance', 3, '[]', '["finance","ops","mcp_server"]', 1778431328);
UPDATE role_hierarchy SET level = 3, can_provision_role_ids = '[]', allowed_modules = '["finance","ops","mcp_server"]' WHERE role_id = 'role-finance';
INSERT OR IGNORE INTO role_hierarchy (role_id, level, can_provision_role_ids, allowed_modules, created_at) VALUES ('role-legal', 3, '[]', '["legal","ops","mcp_server"]', 1778431328);
UPDATE role_hierarchy SET level = 3, can_provision_role_ids = '[]', allowed_modules = '["legal","ops","mcp_server"]' WHERE role_id = 'role-legal';
INSERT OR IGNORE INTO role_hierarchy (role_id, level, can_provision_role_ids, allowed_modules, created_at) VALUES ('role-tech', 3, '[]', '["tech","ops","mcp_server"]', 1778431328);
UPDATE role_hierarchy SET level = 3, can_provision_role_ids = '[]', allowed_modules = '["tech","ops","mcp_server"]' WHERE role_id = 'role-tech';
INSERT OR IGNORE INTO role_hierarchy (role_id, level, can_provision_role_ids, allowed_modules, created_at) VALUES ('role-acq', 3, '[]', '["acquisition","mcp_server"]', 1778431328);
UPDATE role_hierarchy SET level = 3, can_provision_role_ids = '[]', allowed_modules = '["acquisition","mcp_server"]' WHERE role_id = 'role-acq';
INSERT OR IGNORE INTO role_hierarchy (role_id, level, can_provision_role_ids, allowed_modules, created_at) VALUES ('role-emp', 4, '[]', '[]', 1778431328);
UPDATE role_hierarchy SET level = 4, can_provision_role_ids = '[]', allowed_modules = '[]' WHERE role_id = 'role-emp';
INSERT OR IGNORE INTO role_hierarchy (role_id, level, can_provision_role_ids, allowed_modules, created_at) VALUES ('role-agent', 3, '[]', '["mcp_server"]', 1778431328);
UPDATE role_hierarchy SET level = 3, can_provision_role_ids = '[]', allowed_modules = '["mcp_server"]' WHERE role_id = 'role-agent';

-- 3. Permissions
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-employee', 'view_employee', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-employee', 'edit_employee', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-delete-employee', 'delete_employee', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-payroll', 'view_payroll', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-payroll', 'edit_payroll', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-appointments', 'view_appointments', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-appointments', 'edit_appointments', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-legal-tracker', 'view_legal_tracker', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-legal-tracker', 'edit_legal_tracker', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-sectors', 'view_sectors', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-sectors', 'edit_sectors', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-transactions', 'view_transactions', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-create-transaction', 'create_transaction', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-approve-transaction', 'approve_transaction', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-invoices', 'view_invoices', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-create-invoice', 'create_invoice', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-fund-requests', 'view_fund_requests', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-approve-fund-request', 'approve_fund_request', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-accounts', 'view_accounts', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-accounts', 'edit_accounts', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-pl-reports', 'view_pl_reports', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-agreements', 'view_agreements', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-create-agreement', 'create_agreement', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-sign-agreement', 'sign_agreement', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-compliance', 'view_compliance', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-compliance', 'edit_compliance', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-ip', 'view_ip', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-ip', 'edit_ip', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-projects', 'view_projects', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-projects', 'edit_projects', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-tasks', 'view_tasks', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-create-task', 'create_task', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-task', 'edit_task', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-deployments', 'view_deployments', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-trigger-deployment', 'trigger_deployment', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-campaigns', 'view_campaigns', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-campaigns', 'edit_campaigns', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-leads', 'view_leads', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-edit-leads', 'edit_leads', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-provision-user', 'provision_user', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-deactivate-user', 'deactivate_user', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-approve-reset', 'approve_reset', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-reassign-ownership', 'reassign_ownership', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-view-audit-logs', 'view_audit_logs', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-manage-roles', 'manage_roles', 1778431328);
INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('perm-manage-api-keys', 'manage_api_keys', 1778431328);

-- 4. Role ↔ Permission grants (CEO gets all)
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-employee');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-employee');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-delete-employee');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-payroll');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-payroll');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-appointments');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-appointments');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-legal-tracker');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-legal-tracker');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-sectors');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-sectors');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-transactions');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-create-transaction');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-approve-transaction');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-invoices');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-create-invoice');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-fund-requests');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-approve-fund-request');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-accounts');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-accounts');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-pl-reports');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-agreements');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-create-agreement');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-sign-agreement');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-compliance');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-compliance');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-ip');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-ip');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-projects');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-projects');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-tasks');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-create-task');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-task');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-deployments');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-trigger-deployment');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-campaigns');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-campaigns');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-leads');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-edit-leads');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-provision-user');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-deactivate-user');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-approve-reset');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-reassign-ownership');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-view-audit-logs');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-manage-roles');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-ceo', 'perm-manage-api-keys');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-hr', 'perm-view-employee');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-hr', 'perm-edit-employee');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-hr', 'perm-view-payroll');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-hr', 'perm-view-appointments');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-hr', 'perm-edit-appointments');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-hr', 'perm-view-sectors');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-hr', 'perm-provision-user');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-hr', 'perm-deactivate-user');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-hr', 'perm-approve-reset');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES ('role-hr', 'perm-view-audit-logs');

-- 5. CEO user account
INSERT OR IGNORE INTO users_logins (id, email, username, name, password_hash, role_id, is_active, created_at, failed_attempts) VALUES ('user-ceo-001', 'ceo@godwinausten.org', 'ceo', 'Saad Naik', 'c2d5d46c76a18cd23a4a1d0c27ae02335b0a992561c5dd084db14f6441e3a3ec', 'role-ceo', 1, 1778431328, 0);
UPDATE users_logins SET username = 'ceo', name = 'Saad Naik' WHERE id = 'user-ceo-001';

-- 6. HR Manager user account
INSERT OR IGNORE INTO users_logins (id, email, username, name, password_hash, role_id, is_active, created_at, created_by_user_id, failed_attempts) VALUES ('user-hr-001', 'hr@godwinausten.org', 'hrmanager', 'HR Manager', 'e0fb69c10d32ede2acf1e081c2d7ac65c006e4e69680e077d0baf180d7d3b9d3', 'role-hr', 1, 1778431328, 'user-ceo-001', 0);
UPDATE users_logins SET username = 'hrmanager', name = 'HR Manager' WHERE id = 'user-hr-001';

-- 7. CEO owns HR Manager (CEO owns themselves too, for symmetry)
INSERT OR IGNORE INTO user_ownership (user_id, owner_user_id, assigned_at, assigned_by_user_id) VALUES ('user-ceo-001', 'user-ceo-001', 1778431328, 'user-ceo-001');
INSERT OR IGNORE INTO user_ownership (user_id, owner_user_id, assigned_at, assigned_by_user_id) VALUES ('user-hr-001', 'user-ceo-001', 1778431328, 'user-ceo-001');

-- 8. App Access
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_hr', 'user-ceo-001', 'hr', 'admin', 1778431328);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_finance', 'user-ceo-001', 'finance', 'admin', 1778431328);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_legal', 'user-ceo-001', 'legal', 'admin', 1778431328);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_ops', 'user-ceo-001', 'ops', 'admin', 1778431328);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_acquisition', 'user-ceo-001', 'acquisition', 'admin', 1778431328);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_ceo_tech', 'user-ceo-001', 'tech', 'admin', 1778431328);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_hr_hr', 'user-hr-001', 'hr', 'admin', 1778431328);
INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) VALUES ('acc_hr_ops', 'user-hr-001', 'ops', 'admin', 1778431328);

PRAGMA foreign_keys = ON;

-- ✅ Seed complete.
-- CEO:        ceo@godwinausten.org / ChangeMe_CEO_2026!
-- HR Manager: hr@godwinausten.org / ChangeMe_HR_2026!
-- IMPORTANT: Change passwords immediately after first login!
