/**
 * scratch/seed_rbac.ts
 *
 * Seeds the role_hierarchy table with the correct levels and module access,
 * and creates the foundational CEO + HR_Manager user accounts.
 *
 * Run via Wrangler:
 *   npx wrangler d1 execute office-db --local --file=scratch/seed_rbac.sql
 *
 * Or generate the SQL from this script:
 *   npx tsx scratch/seed_rbac.ts > scratch/seed_rbac.sql
 *
 * Usage: npx tsx scratch/seed_rbac.ts | npx wrangler d1 execute office-db --local --command=-
 */

import crypto from 'crypto';

// ── Utility: SHA-256 hex (sync, Node.js) ─────────────────────────────────────
function sha256(input: string): string {
  return crypto.createHash('sha256').update(input).digest('hex');
}

// ── Configuration — change these before first run ─────────────────────────────
const CEO_EMAIL = 'ceo@godwinausten.org';
const CEO_PASSWORD = 'ChangeMe_CEO_2026!';   // ← CHANGE before seeding production

const HR_EMAIL = 'hr@godwinausten.org';
const HR_PASSWORD = 'ChangeMe_HR_2026!';    // ← CHANGE before seeding production

// ── Role IDs (must match what's already in roles table from migration) ────────
const ROLES = [
  { id: 'role-ceo', name: 'CEO' },
  { id: 'role-director', name: 'Director' },
  { id: 'role-legal', name: 'Legal_Officer' },
  { id: 'role-emp', name: 'Employee' },
  { id: 'role-agent', name: 'Agent' },
] as const;

// ── Hierarchy configuration ───────────────────────────────────────────────────
const HIERARCHY = [
  {
    roleId: 'role-ceo',
    level: 1,
    canProvisionRoleIds: ['role-ceo', 'role-director', 'role-legal', 'role-emp', 'role-agent'],
    allowedModules: ['hr', 'finance', 'legal', 'ops', 'acquisition', 'tech', 'mcp_server'],
  },
  {
    roleId: 'role-director',
    level: 2,
    canProvisionRoleIds: ['role-emp'],
    allowedModules: ['acquisition', 'tech', 'ops', 'mcp_server'],
  },
  {
    roleId: 'role-legal',
    level: 3,
    canProvisionRoleIds: [],
    allowedModules: ['legal', 'ops', 'mcp_server'],
  },
  {
    roleId: 'role-emp',
    level: 4,
    canProvisionRoleIds: [],
    allowedModules: [],
  },
  {
    roleId: 'role-agent',
    level: 3,
    canProvisionRoleIds: [],
    allowedModules: ['mcp_server'],
  },
] as const;

// ── Permissions to seed ───────────────────────────────────────────────────────
const PERMISSIONS = [
  // HR module
  'view_employee', 'edit_employee', 'delete_employee',
  'view_payroll', 'edit_payroll',
  'view_appointments', 'edit_appointments',
  'view_legal_tracker', 'edit_legal_tracker',
  'view_sectors', 'edit_sectors',
  // Finance module
  'view_transactions', 'create_transaction', 'approve_transaction',
  'view_invoices', 'create_invoice',
  'view_fund_requests', 'approve_fund_request',
  'view_accounts', 'edit_accounts',
  'view_pl_reports',
  // Legal module
  'view_agreements', 'create_agreement', 'sign_agreement',
  'view_compliance', 'edit_compliance',
  'view_ip', 'edit_ip',
  // Tech module
  'view_projects', 'edit_projects',
  'view_tasks', 'create_task', 'edit_task',
  'view_deployments', 'trigger_deployment',
  // Acquisition module
  'view_campaigns', 'edit_campaigns',
  'view_leads', 'edit_leads',
  // Admin / account management
  'provision_user', 'deactivate_user', 'approve_reset', 'reassign_ownership',
  'view_audit_logs', 'manage_roles', 'manage_api_keys',
] as const;

// ── User IDs ──────────────────────────────────────────────────────────────────
const CEO_USER_ID = 'user-ceo-001';
const HR_USER_ID = 'user-hr-001';

// ── Generate SQL ──────────────────────────────────────────────────────────────
const now = Math.floor(Date.now() / 1000);

const lines: string[] = [
  'PRAGMA foreign_keys = OFF;',
  '-- ============================================================',
  '-- office RBAC Seed — auto-generated by scratch/seed_rbac.ts',
  '-- ============================================================',
  '',
  '-- 1. Roles',
];

for (const r of ROLES) {
  lines.push(
    `INSERT OR IGNORE INTO roles (id, name, created_at) VALUES ('${r.id}', '${r.name}', ${now});`
  );
}

lines.push('', '-- 2. Role Hierarchy (Skipped)');


lines.push('', '-- 3. Permissions');
for (const p of PERMISSIONS) {
  const permId = `perm-${p.replace(/_/g, '-')}`;
  lines.push(
    `INSERT OR IGNORE INTO permissions (id, name, created_at) VALUES ('${permId}', '${p}', ${now});`
  );
}

lines.push('', '-- 4. Role ↔ Permission grants (Skipped)');


lines.push('', '-- 5. CEO user account');
lines.push(
  `INSERT OR IGNORE INTO users_logins ` +
  `(id, email, username, name, password_hash, role_id, is_active, created_at, failed_attempts) VALUES ` +
  `('${CEO_USER_ID}', '${CEO_EMAIL}', 'ceo', 'Saad Naik', '${sha256(CEO_PASSWORD)}', 'role-ceo', 1, ${now}, 0);`
);
lines.push(
  `UPDATE users_logins SET username = 'ceo', name = 'Saad Naik' WHERE id = '${CEO_USER_ID}';`
);

lines.push('', '-- 6. HR Manager user account');
lines.push(
  `INSERT OR IGNORE INTO users_logins ` +
  `(id, email, username, name, password_hash, role_id, is_active, created_at, created_by_user_id, failed_attempts) VALUES ` +
  `('${HR_USER_ID}', '${HR_EMAIL}', 'hrmanager', 'HR Manager', '${sha256(HR_PASSWORD)}', 'role-hr', 1, ${now}, '${CEO_USER_ID}', 0);`
);
lines.push(
  `UPDATE users_logins SET username = 'hrmanager', name = 'HR Manager' WHERE id = '${HR_USER_ID}';`
);

lines.push('', '-- 7. CEO owns HR Manager (CEO owns themselves too, for symmetry)');
lines.push(
  `INSERT OR IGNORE INTO user_ownership (user_id, owner_user_id, assigned_at, assigned_by_user_id) ` +
  `VALUES ('${CEO_USER_ID}', '${CEO_USER_ID}', ${now}, '${CEO_USER_ID}');`
);
lines.push(
  `INSERT OR IGNORE INTO user_ownership (user_id, owner_user_id, assigned_at, assigned_by_user_id) ` +
  `VALUES ('${HR_USER_ID}', '${CEO_USER_ID}', ${now}, '${CEO_USER_ID}');`
);

lines.push('', '-- 8. App Access');
const CEO_APPS = ['hr', 'finance', 'legal', 'ops', 'acquisition', 'tech'];
for (const app of CEO_APPS) {
  lines.push(
    `INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) ` +
    `VALUES ('acc_ceo_${app}', '${CEO_USER_ID}', '${app}', 'admin', ${now});`
  );
}
const HR_APPS = ['hr', 'ops'];
for (const app of HR_APPS) {
  lines.push(
    `INSERT OR IGNORE INTO user_app_access (id, user_id, app_name, access_level, created_at) ` +
    `VALUES ('acc_hr_${app}', '${HR_USER_ID}', '${app}', 'admin', ${now});`
  );
}

lines.push('', '-- 9. CEO Granular Permissions (Full Access)');
const APP_FEATURES: Record<string, string[]> = {
  hr: ['employees', 'appointments', 'payroll', 'resets', 'tasks'],
  finance: ['transactions', 'invoices', 'fund_requests', 'accounts', 'pl_reports'],
  legal: ['agreements', 'compliance', 'ip', 'requests', 'sops', 'templates'],
  tech: ['projects', 'tasks', 'deployments', 'issues', 'releases', 'environments'],
  acquisition: ['campaigns', 'leads', 'content', 'funnels'],
  ops: ['core', 'admin', 'audit'],
  crm: ['tickets', 'planner', 'docs']
};

for (const [app, features] of Object.entries(APP_FEATURES)) {
  for (const feature of features) {
    const permId = `perm_ceo_${app}_${feature}`;
    lines.push(
      `INSERT OR IGNORE INTO user_app_permissions (id, user_id, app_name, feature, can_view, can_edit, can_delete, created_at, updated_at) ` +
      `VALUES ('${permId}', '${CEO_USER_ID}', '${app}', '${feature}', 1, 1, 1, ${now}, ${now});`
    );
  }
}

lines.push('', 'PRAGMA foreign_keys = ON;');
lines.push('', '-- ✅ Seed complete.');
lines.push('-- CEO:        ' + CEO_EMAIL + ' / ' + CEO_PASSWORD);
lines.push('-- HR Manager: ' + HR_EMAIL + ' / ' + HR_PASSWORD);
lines.push('-- IMPORTANT: Change passwords immediately after first login!');

console.log(lines.join('\n'));
