import { Env } from '../index';
import { fileDocument, letterhead, reportKey, safeSegment, type FiledDocument } from './file';
import { Column, StatementDoc, formatMoney } from './layout';
import {
  journalReport,
  ledgerReport,
  MAX_DETAIL_ROWS,
  type DateRange,
  type JournalReport,
  type LedgerAccountReport,
  type LedgerReport,
  type LedgerScope,
} from './reports';

/**
 * The two ledger reports, rendered as PDFs and filed in R2.
 *
 * A *report*, not a statement: a statement summarises a period into a handful
 * of figures, whereas these transcribe what is actually in the books —
 * every entry, both sides, the narration, and what each account did. That is
 * what gets asked for when an auditor is in the room.
 *
 * The consequence is that "all time" is a normal request rather than an edge
 * case, and the renderer is built for it: headers repeat across pages, the
 * detail listing is bounded and says so when it bites, and every total is
 * computed over the whole matching set rather than over what fitted.
 */

export type ReportKind = 'journal' | 'ledger';

export interface ReportResult extends FiledDocument {
  kind: ReportKind;
  title: string;
  /** What the report covers, in words. Echoed back to whoever asked. */
  coverage: string;
  figures: Record<string, number | string | boolean | null>;
}

const humanDate = (iso: string) =>
  new Date(`${iso}T00:00:00Z`).toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC',
  });

/**
 * The period, said in words.
 *
 * Four cases, and all four are reachable from the UI and from the agent: a
 * closed range, either half-open range, and no range at all. "For the period
 * undefined to undefined" is the failure this exists to prevent.
 */
function periodPhrase(range: DateRange): string {
  const { startDate, endDate } = range;
  if (startDate && endDate) return `For the period ${humanDate(startDate)} to ${humanDate(endDate)}`;
  if (startDate) return `From ${humanDate(startDate)} onwards — every entry since`;
  if (endDate) return `Everything on record up to ${humanDate(endDate)}`;
  return 'Complete history — every entry on record';
}

/** The same four cases, as a filename-safe key segment. */
function periodKey(range: DateRange): string {
  const { startDate, endDate } = range;
  if (startDate && endDate) return `${startDate}_to_${endDate}`;
  if (startDate) return `from_${startDate}`;
  if (endDate) return `to_${endDate}`;
  return 'all_time';
}

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

/** Validates a range. Either end may be absent; a backwards range may not. */
export function validateRange(range: DateRange): string | null {
  if (range.startDate && !DATE_RE.test(range.startDate)) return 'startDate must be YYYY-MM-DD.';
  if (range.endDate && !DATE_RE.test(range.endDate)) return 'endDate must be YYYY-MM-DD.';
  if (range.startDate && range.endDate && range.startDate > range.endDate) {
    return 'The start date is after the end date.';
  }
  return null;
}

export async function openDoc(env: Env, title: string, subtitle: string, requestedVia: string, source: string) {
  const head = await letterhead(env);
  return StatementDoc.create({
    title,
    subtitle,
    organisation: head.organisation + (head.ntn ? `  ·  NTN ${head.ntn}` : ''),
    currency: head.currency,
    provenance:
      `Generated by Pleiades from ${source} on ` +
      `${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC · ${requestedVia} · ` +
      `amounts in ${head.currency}`,
    draft: true,
  });
}

/* ── The general journal ─────────────────────────────────────────────────── */

/**
 * The classic journal layout: debits first, credits indented beneath them, and
 * the narration in full underneath. Account names live in Particulars rather
 * than in a column of their own, which is both the textbook form and the only
 * way to give a compound entry's longest account name room to print.
 */
const JOURNAL_COLS: Column[] = [
  { header: 'Date', width: 56 },
  { header: 'Reference', width: 58 },
  { header: 'Particulars', width: 227 },
  { header: 'Debit', width: 71, align: 'right', mono: true },
  { header: 'Credit', width: 71, align: 'right', mono: true },
];

/**
 * A reference short enough to print.
 *
 * Ids are a prefix and 32 hex characters, which no column on an A4 page can
 * hold — and a full id truncated by the renderer is worse than a short one
 * chosen deliberately, because the reader cannot tell where it was cut. Eight
 * hex digits distinguish every entry any real journal will hold, and the full
 * id stays in the narration line beneath, where there is room for it.
 */
const shortRef = (id: string) => (id.length > 14 ? `${id.slice(0, 12)}\u2026` : id);

export function renderJournal(doc: StatementDoc, r: JournalReport) {
  if (r.empty) {
    doc.note(
      'No journal entries fall within this period, so there is nothing to transcribe. This is a ' +
        'report of absence, not a set of zeroes: if you expected entries here, check the entry ' +
        'dates on the journals rather than reading this as an empty ledger.',
    );
    return;
  }

  doc.section('Summary');
  doc.line('Total debits', r.totalDebit);
  doc.line('Total credits', r.totalCredit);
  doc.total('Difference', Math.round((r.totalDebit - r.totalCredit) * 100) / 100, true);
  doc.note(
    `${r.entryCount} ${r.entryCount === 1 ? 'entry' : 'entries'}` +
      (r.ledgerName ? ` in the ${r.ledgerName} ledger` : '') +
      '. Totals above cover every matching entry, including any the listing below does not reach.' +
      (Math.abs(r.totalDebit - r.totalCredit) > 0.01
        ? ' Debits and credits do not agree across this period, which means at least one entry is ' +
          'incomplete — the entries concerned are marked below.'
        : ' Debits and credits agree.'),
  );

  if (r.unbalanced > 0) {
    doc.note(
      r.unbalanced === 1
        ? '1 entry does not balance on its own. It is marked "does not balance" beneath its narration.'
        : `${r.unbalanced} entries do not balance on their own. Each is marked "does not balance" ` +
          'beneath its narration.',
    );
  }
  if (r.undated > 0) {
    doc.note(
      r.undated === 1
        ? '1 entry carries no entry date. It appears at the end of the listing; a dated range ' +
          'cannot include it at all, which is why it is only ever shown in a complete-history report.'
        : `${r.undated} entries carry no entry date. They appear at the end of the listing; a ` +
          'dated range cannot include them at all, which is why they are only ever shown in a ' +
          'complete-history report.',
    );
  }

  doc.section('Entries');
  doc.beginTable(JOURNAL_COLS, true);

  for (const e of r.entries) {
    doc.nextGroup();
    const debits = e.lines.filter((l) => l.type === 'debit');
    const credits = e.lines.filter((l) => l.type === 'credit');
    const date = e.entryDate ?? '(no date)';

    // One posting line is 13 points and a narration line 11; the narration runs
    // to at most two. Reserved as a block so an entry is never split across a
    // page, which would leave its narration above the wrong entry.
    doc.keepTogether(Math.max(1, e.lines.length) * 13 + 24);

    // An entry with no readable lines at all still prints: it is in the books,
    // and a transcript that silently drops rows is not a transcript.
    if (debits.length === 0 && credits.length === 0) {
      doc.row([date, shortRef(e.id), '(no posting lines recorded)', null, null]);
    }

    debits.forEach((l, i) => {
      doc.row([i === 0 ? date : null, i === 0 ? shortRef(e.id) : null, l.accountName, l.amount, null]);
    });
    credits.forEach((l, i) => {
      const first = debits.length === 0 && i === 0;
      doc.row([first ? date : null, first ? shortRef(e.id) : null, `    ${l.accountName}`, null, l.amount]);
    });

    const meta = [
      e.id,
      e.description || '(no narration recorded)',
      e.ledgerName ? `Ledger: ${e.ledgerName}` : null,
      e.invoiceId ? `Invoice: ${e.invoiceId}` : null,
      e.balanced ? null : `DOES NOT BALANCE — debits ${formatMoney(e.debit)}, credits ${formatMoney(e.credit)}`,
    ].filter(Boolean);
    doc.noteRow(meta.join('  ·  '));
  }

  doc.row(['', '', 'Totals for the entries listed above', r.totalDebit, r.totalCredit], { bold: true });

  if (r.truncated) {
    doc.noteRow(
      `${r.omitted} further ${r.omitted === 1 ? 'entry is' : 'entries are'} not listed: this ` +
        `report prints at most ${MAX_DETAIL_ROWS} rows, which is already more than anyone reads ` +
        'in sequence. The totals above and in the summary cover every matching entry regardless. ' +
        'Narrow the date range, or filter to one ledger, to see the rest in full.',
      { indent: 0, maxLines: 4 },
    );
  }

  doc.endTable();
}

export interface JournalReportRenderRequest extends DateRange {
  ledgerId?: string | null;
  actorUserId: string;
  requestedVia: string;
}

export async function generateJournalReport(
  env: Env,
  req: JournalReportRenderRequest,
): Promise<ReportResult | { error: string }> {
  const range: DateRange = { startDate: req.startDate ?? null, endDate: req.endDate ?? null };
  const invalid = validateRange(range);
  if (invalid) return { error: invalid };

  const data = await journalReport(env, { ...range, ledgerId: req.ledgerId ?? null });

  if (req.ledgerId && !data.ledgerName) {
    return { error: `No ledger with id ${req.ledgerId}.` };
  }

  const title = 'General Journal';
  const subtitle =
    periodPhrase(range) + (data.ledgerName ? `  ·  ${data.ledgerName} ledger` : '');

  const doc = await openDoc(env, title, subtitle, req.requestedVia, 'general_journals');
  renderJournal(doc, data);
  const bytes = await doc.save();

  const periodLabel =
    (data.ledgerName ? `${safeSegment(data.ledgerName)}_` : '') + periodKey(range);

  const figures = {
    entries: data.entryCount,
    totalDebit: data.totalDebit,
    totalCredit: data.totalCredit,
    difference: Math.round((data.totalDebit - data.totalCredit) * 100) / 100,
    unbalanced: data.unbalanced,
    undated: data.undated,
    listed: data.entries.length,
    omitted: data.omitted,
    empty: data.empty,
  };

  const filed = await fileDocument(
    env,
    {
      docType: 'general_journal_report',
      periodLabel,
      bytes,
      actorUserId: req.actorUserId,
      basis: {
        source: 'general_journals',
        startDate: range.startDate,
        endDate: range.endDate,
        ledgerId: req.ledgerId ?? null,
        ledgerName: data.ledgerName,
        requestedVia: req.requestedVia,
        figures,
      },
    },
    (version) => reportKey('journal', 'general_journal', periodLabel, version),
  );
  if ('error' in filed) return filed;

  return {
    ...filed,
    kind: 'journal',
    title,
    coverage: subtitle,
    figures,
  };
}

/* ── The ledger accounts ─────────────────────────────────────────────────── */

const LEDGER_COLS: Column[] = [
  { header: 'Date', width: 56 },
  { header: 'Reference', width: 58 },
  { header: 'Particulars', width: 157 },
  { header: 'Debit', width: 66, align: 'right', mono: true },
  { header: 'Credit', width: 66, align: 'right', mono: true },
  { header: 'Balance', width: 80, align: 'right', mono: true },
];

/** A signed, debit-positive balance printed the way a ledger prints one. */
const sided = (n: number) =>
  Math.abs(n) < 0.005 ? '0.00' : `${formatMoney(Math.abs(n))} ${n > 0 ? 'Dr' : 'Cr'}`;

function renderLedgerAccount(doc: StatementDoc, a: LedgerAccountReport, range: DateRange) {
  doc.subheading(
    a.accountName,
    // The book's name as it stands. Appending "ledger" turns the common case,
    // a book called "Main Ledger", into "Main Ledger ledger".
    [a.accountType, a.ledgerName].filter(Boolean).join('  ·  '),
  );

  doc.beginTable(LEDGER_COLS);

  doc.row([
    range.startDate ?? '',
    '',
    range.startDate ? 'Balance b/d' : 'Opening balance (from inception)',
    null,
    null,
    sided(a.openingBalance),
  ]);

  for (const e of a.entries) {
    doc.row([
      e.entryDate ?? '(no date)',
      shortRef(e.id),
      // Contra first, narration after: reading down a ledger page, the question
      // is always "what was this against", and the narration qualifies it.
      [e.contra, e.description].filter(Boolean).join(' — '),
      e.debit || null,
      e.credit || null,
      sided(e.balance),
    ]);
  }

  if (a.truncated) {
    doc.noteRow(
      `${a.omitted} further ${a.omitted === 1 ? 'entry is' : 'entries are'} not listed for this ` +
        'account. The totals and closing balance below still cover every one of them.',
      { indent: 0, maxLines: 3 },
    );
  }

  doc.row(['', '', 'Movement in the period', a.totalDebit, a.totalCredit, ''], { bold: true });
  doc.row([
    range.endDate ?? '',
    '',
    'Balance c/d',
    null,
    null,
    sided(a.closingBalance),
  ], { bold: true });

  doc.endTable();
}

export function renderLedger(doc: StatementDoc, r: LedgerReport) {
  if (r.empty) {
    doc.note(
      r.skippedEmpty > 0
        ? `None of the ${r.skippedEmpty} accounts in scope carries a balance or moved in this ` +
          'period, so there is nothing to show. This is a report of absence, not a set of zeroes.'
        : 'There are no accounts in scope, so there is nothing to report.',
    );
    return;
  }

  doc.section('Summary');
  doc.line('Total debits', r.totalDebit);
  doc.line('Total credits', r.totalCredit);
  doc.total('Difference', r.net, true);
  doc.note(
    `${r.accounts.length} ${r.accounts.length === 1 ? 'account' : 'accounts'} shown` +
      (r.skippedEmpty > 0
        ? `; ${r.skippedEmpty} further ${r.skippedEmpty === 1 ? 'account is' : 'accounts are'} ` +
          'omitted as they neither moved in this period nor carry an opening balance'
        : '') +
      '. ' +
      (Math.abs(r.net) > 0.01
        ? 'Debits and credits across these accounts do not agree. Where the report covers every ' +
          'account and the whole history, that difference is a real defect in the books and is ' +
          'worth tracing before this is relied on; over a subset or a date range it is expected, ' +
          'because the other side of an entry may sit outside what was asked for.'
        : 'Debits and credits agree across the accounts shown.'),
  );
  if (r.truncated) {
    doc.note(
      `This report prints at most ${MAX_DETAIL_ROWS} rows in total, and that limit was reached. ` +
        'Every opening balance, movement total and closing balance below is still computed over ' +
        'every entry; it is the line-by-line listing that stops short, and each account says so ' +
        'where it does. Narrow the date range or report one account at a time for the full detail.',
    );
  }

  doc.section('Accounts');
  for (const a of r.accounts) renderLedgerAccount(doc, a, r.range);
}

export interface LedgerReportRenderRequest extends DateRange {
  scope: LedgerScope;
  accountId?: string | null;
  ledgerId?: string | null;
  actorUserId: string;
  requestedVia: string;
}

export async function generateLedgerReport(
  env: Env,
  req: LedgerReportRenderRequest,
): Promise<ReportResult | { error: string }> {
  const range: DateRange = { startDate: req.startDate ?? null, endDate: req.endDate ?? null };
  const invalid = validateRange(range);
  if (invalid) return { error: invalid };

  const data = await ledgerReport(env, {
    ...range,
    scope: req.scope,
    accountId: req.accountId ?? null,
    ledgerId: req.ledgerId ?? null,
  });
  if ('error' in data) return data;

  const title =
    data.scope === 'all' ? 'Ledger — All Accounts'
    : data.scope === 'ledger' ? `Ledger — ${data.scopeLabel}`
    : `Ledger Account — ${data.scopeLabel}`;
  const subtitle = periodPhrase(range);

  const doc = await openDoc(env, title, subtitle, req.requestedVia, 'general_journals');
  renderLedger(doc, data);
  const bytes = await doc.save();

  const scopeKey =
    data.scope === 'all' ? 'all-accounts' : safeSegment(`${data.scope}-${data.scopeLabel}`);
  const periodLabel = `${scopeKey}_${periodKey(range)}`;

  const figures = {
    scope: data.scope,
    scopeLabel: data.scopeLabel,
    accounts: data.accounts.length,
    skippedEmpty: data.skippedEmpty,
    totalDebit: data.totalDebit,
    totalCredit: data.totalCredit,
    difference: data.net,
    truncated: data.truncated,
    empty: data.empty,
    // A single-account report has one closing balance, and it is the figure
    // the person asking almost always wanted. Recorded so the listing and the
    // agent can both quote it without re-reading the PDF.
    closingBalance: data.accounts.length === 1 ? data.accounts[0].closingBalance : null,
  };

  const filed = await fileDocument(
    env,
    {
      docType: 'ledger_report',
      periodLabel,
      bytes,
      actorUserId: req.actorUserId,
      basis: {
        source: 'general_journals',
        startDate: range.startDate,
        endDate: range.endDate,
        scope: data.scope,
        accountId: req.accountId ?? null,
        ledgerId: req.ledgerId ?? null,
        requestedVia: req.requestedVia,
        figures,
      },
    },
    (version) => reportKey('ledger', 'ledger', periodLabel, version),
  );
  if ('error' in filed) return filed;

  return {
    ...filed,
    kind: 'ledger',
    title,
    coverage: `${subtitle}  ·  ${data.scopeLabel}`,
    figures,
  };
}

/** Both report types, for validation and for the UI's picker. */
export const REPORT_DOC_TYPES = ['general_journal_report', 'ledger_report'] as const;
